version: "3.8"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  graph-service:
    build:
      context: ./graph_service
      dockerfile: Dockerfile
    container_name: graph_service
    ports:
      - "8002:8002"
    environment:
      # Redis URL을 환경변수로 주입
      REDIS_URL: "redis://redis:6379"
      # (필요하다면) CONFIG_PATH, INDEX_PATH 등도
    depends_on:
      - redis
    restart: unless-stopped
