version: "3.8"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  # runtime_infer:
  #   build:
  #     context: ./app
  #     dockerfile: runtime/Dockerfile
  #   container_name: searchforest-infer
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
  #     - ./app/indices:/app/indices:ro  # 인덱스 실시간 사용
  #   ports:
  #     - "8004:8004"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  graph-service:
    build:
      context: ./app/services/graph_service
      dockerfile: Dockerfile
    container_name: graph_service
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379
      - INFER_URL=http://host.docker.internal:8004
    depends_on:
      - redis
    restart: unless-stopped

  papers-service:
    build:
      context: ./app/services/papers_service
      dockerfile: Dockerfile
    container_name: papers_service
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GRAPH_URL=http://graph-service:8002
    depends_on:
      - redis
      - graph-service
    restart: unless-stopped
    volumes:
      - ./app/data:/app/data:ro

