version: "3.8"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  papers-service:
    build:
      context: ./app/services/papers_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - searchforest-ai

  graph-service:
    build:
      context: ./app/services/graph_service
      dockerfile: Dockerfile
    container_name: graph_service
    ports:
      - "8002:8002"
    environment:
      # Redis URL을 환경변수로 주입
      REDIS_URL: "redis://redis:6379"
      # (필요하다면) CONFIG_PATH, INDEX_PATH 등도
    depends_on:
      - redis
      - searchforest-ai
    restart: unless-stopped
  
  runtime_infer:
    build:
      context: ./app/runtime
      dockerfile: app/runtime/Dockerfile
    container_name: searchforest-infer
    runtime: nvidia            # GPU 전달
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./indices:/workspace/indices  # 인덱스 실시간 사용
    ports:
      - "8004:8004"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

