name: cgsum
channels:
  - defaults
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.6
  - cudatoolkit=10.0
  - pip
  - pip:
    - dgl==0.4.3.cuda10.0
    - fastNLP==0.5.0
    - rouge==1.0.0
    - pyrouge==0.1.3
    - fastapi
    - uvicorn[standard]
    - pydantic
    - tqdm
  - pytorch=1.1.0
  - torchvision=0.3.0
