name: searchforest-cpu
dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy==1.21.6
      - dgl==0.4.3
      - fastNLP==0.5.0
      - rouge==1.0.0
      - pyrouge==0.1.3
      - fastapi
      - uvicorn[standard]
      - pydantic
      - tqdm
      - python-dotenv
      - huggingface_hub
      - datasets
      - dotenv
      - datasets
# pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
# pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl
# pip install torch==1.7.1+cpu torchvision==0.8.2+cpu -f https://download.pytorch.org/whl/torch_stable.html


