name: cgsum_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.1.0
  - cudatoolkit=10.0
  - pip
  - pip:
      - dgl==0.4.3
      - fastNLP==0.5.0
      - rouge==1.0.0
      - pyrouge==0.1.3
      - tqdm
      - spacy==2.3.9

      - fastapi
      - uvicorn[standard]
      - pydantic
      - python-dotenv
      - huggingface_hub
      - datasets