name: Publish Docker images to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'graph_service/**'
      - 'papers_service/**'
      - 'sum_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # checkout
      packages: write      # GHCR push
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}

    strategy:
      matrix:
        service: [graph, papers, sum]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}-service image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}_service
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.service }}-service:latest
