name: Publish Docker images to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'graph_service/**'
      - 'papers_service/**'
      - 'sum_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # checkout
      packages: write      # GHCR push
    env:
      REGISTRY: ghcr.io/soopsong

    strategy:
      matrix:
        # 디렉터리 vs 리포지터리 이름을 명시적으로 매핑
        include:
          - dir: graph_service
            repo: graph-service
          - dir: papers_service
            repo: papers-service
          - dir: sum_service
            repo: sum-service

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR via PAT
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hyun_hyang
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push ${{ matrix.repo }} image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.dir }}
          file: ./${{ matrix.dir }}/Dockerfile
          push: true
          tags: ghcr.io/soopsong/${{ matrix.repo }}:latest