name: Publish Docker images to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'graph_service/**'
      - 'papers_service/**'
      - 'sum_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # checkout
      packages: write      # GHCR push
    env:
      REGISTRY: ghcr.io/soopsong

    strategy:
      matrix:
        # 서비스 디렉터리 및 이미지 이름
        service:
          - graph_service
          - papers_service
          - sum_service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR via PAT
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hyun_hyang
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.service }}:latest
