name: Publish Docker images to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - 'graph_service/**'
      - 'papers_service/**'
      # - 'sum_service/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # checkout 권한
      packages: write       # GHCR 푸시 권한

    env:
      REGISTRY: ghcr.io/soopsong

    strategy:
      matrix:
        include:
          - dir: app/services/graph_service
            repo: graph-service
          - dir: app/services/papers_service
            repo: papers-service
          # - dir: app/services/sum_service
          #   repo: sum-service

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR via PAT (manual)
        run: echo "${{ secrets.PASSWORD }}" | docker login ghcr.io -u hyun_hyang --password-stdin

      - name: Build & push ${{ matrix.repo }} image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.dir }}
          file:    ./${{ matrix.dir }}/Dockerfile
          push:    true
          tags:    ${{ env.REGISTRY }}/${{ matrix.repo }}:latest