name: Publish Docker images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'graph_service/**'
      - 'papers_service/**'
      - 'sum_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # for checkout
      packages: write         # for GHCR push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Graph Service image
        uses: docker/build-push-action@v4
        with:
          context: ./graph_service
          push: true
          tags: |
            ghcr.io/soopsong/graph-service:latest

      - name: Build & push Papers Service image
        uses: docker/build-push-action@v4
        with:
          context: ./papers_service
          push: true
          tags: |
            ghcr.io/soopsong/papers-service:latest

      - name: Build & push Summ Service image
        uses: docker/build-push-action@v4
        with:
          context: ./sum_service
          push: true
          tags: |
            ghcr.io/soopsong/sum-service:latest
